sudo: false
language: generic

cache:
  apt: true

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - libatlas-base-dev
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libatlas-base-dev
          sources: *sources

install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/ericniebler/range-v3.git third_party/range-v3
  - git clone https://github.com/foonathan/debug_assert.git third_party/debug_assert

script:
  - CXXFLAGS="-isystem../third_party/range-v3/include -isystem../third_party/debug_assert" make test
