sudo: false
language: generic

cache:
  apt: true

matrix:
  include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
    - env: CXX=clang++-3.9 CC=clang-3.9
      addons:
        apt:
          packages:
            - clang-3.9
          sources: *sources

install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/ericniebler/range-v3.git third_party/range-v3
  - git clone https://github.com/foonathan/debug_assert.git third_party/debug_assert

script:
  - CXXFLAGS="-isystem../third_party/range-v3/include -isystem../third_party/debug_assert" make test
