install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/ericniebler/range-v3.git third_party/range-v3
  - git clone https://github.com/foonathan/debug_assert.git third_party/debug_assert
language: cpp
compiler:
  - clang
  - gcc
script:
  - CXXFLAGS="-isystem../third_party/range-v3/include -isystem../third_party/debug_assert" make test
